profile:
  group:
    - [book, report, manual]

bibliography: references.bib

number-depth: 2

filters: 
  - pseudocode

pseudocode:
  caption-prefix: "Algorithm"
  reference-prefix: "Algorithm"
  caption-number: true
  caption-align: left