project:
  type: book

book:
  downloads: pdf
  title: "Advanced Praktika SoSe 26 Notes"
  author: "Igor Dimitrov"
  date: "4/21/2026"
  chapters:
    - index.qmd
    - part: "Notes"
      chapters:
      - notes/project_setup.qmd
      - notes/project_overview.qmd
      - notes/conversions.qmd
      - notes/mixed_ir.qmd
      - notes/experiments.qmd
    - report.qmd

    # - intro.qmd
    # - summary.qmd
    # - references.qmd



bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    include-in-header: 
      - mathjax-macros.html
    mermaid-format: js
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
    mermaid-format: png



number-depth: 2