<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Implementing the Experiments &amp; Robustness Improvements – Advanced Praktika SoSe 26 Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/experiment_plan.html" rel="next">
<link href="../notes/mixed_ir.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bf132de45b538d253cd2e2da5fec6016.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
window.MathJax = {
  tex: {
    macros: {
      norm: ["\\left\\lVert #1 \\right\\rVert", 1],
      normsub: ["\\left\\lVert #1 \\right\\rVert_{#2}", 2] 
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/project_setup.html">Notes</a></li><li class="breadcrumb-item"><a href="../notes/experiments.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Implementing the Experiments &amp; Robustness Improvements</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Advanced Praktika SoSe 26 Notes</a> 
        <div class="sidebar-tools-main">
    <a href="../Advanced-Praktika-SoSe-26-Notes.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Notes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/project_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Project Setup</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/project_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Project Summary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/conversions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Conversions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/mixed_ir.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Implementation of the Mixed IR Algorithm</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/experiments.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Implementing the Experiments &amp; Robustness Improvements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/experiment_plan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mixed-Precision Iterative Refinement: Experiment Plan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Experimental Framework</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Report</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/gdb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">GDB usage Notes</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#temporary-matrix-generator" id="toc-temporary-matrix-generator" class="nav-link active" data-scroll-target="#temporary-matrix-generator"><span class="header-section-number">5.1</span> Temporary Matrix Generator</a></li>
  <li><a href="#matrix-generator-supervisor-version" id="toc-matrix-generator-supervisor-version" class="nav-link" data-scroll-target="#matrix-generator-supervisor-version"><span class="header-section-number">5.2</span> Matrix Generator Supervisor Version</a>
  <ul class="collapse">
  <li><a href="#nonsymmetric-generator" id="toc-nonsymmetric-generator" class="nav-link" data-scroll-target="#nonsymmetric-generator">Nonsymmetric Generator</a></li>
  </ul></li>
  <li><a href="#configurable-test-problem-construction" id="toc-configurable-test-problem-construction" class="nav-link" data-scroll-target="#configurable-test-problem-construction"><span class="header-section-number">5.3</span> Configurable test-problem Construction</a>
  <ul class="collapse">
  <li><a href="#three-right-hand-side-modes" id="toc-three-right-hand-side-modes" class="nav-link" data-scroll-target="#three-right-hand-side-modes">Three Right-hand-side Modes</a></li>
  <li><a href="#test-problem-options" id="toc-test-problem-options" class="nav-link" data-scroll-target="#test-problem-options">Test-problem Options</a></li>
  <li><a href="#linear-system-representation" id="toc-linear-system-representation" class="nav-link" data-scroll-target="#linear-system-representation">Linear-system Representation</a></li>
  <li><a href="#shared-complete_problem-function" id="toc-shared-complete_problem-function" class="nav-link" data-scroll-target="#shared-complete_problem-function">Shared <code>complete_problem</code> function</a></li>
  <li><a href="#high-precision-reference-solve" id="toc-high-precision-reference-solve" class="nav-link" data-scroll-target="#high-precision-reference-solve">High-precision reference solve</a></li>
  <li><a href="#matrix-generator-interfaces" id="toc-matrix-generator-interfaces" class="nav-link" data-scroll-target="#matrix-generator-interfaces">Matrix-generator interfaces</a></li>
  <li><a href="#usage-examples" id="toc-usage-examples" class="nav-link" data-scroll-target="#usage-examples">Usage Examples</a></li>
  </ul></li>
  <li><a href="#error-metrics-helper" id="toc-error-metrics-helper" class="nav-link" data-scroll-target="#error-metrics-helper"><span class="header-section-number">5.4</span> Error Metrics Helper</a></li>
  <li><a href="#first-convergence-test" id="toc-first-convergence-test" class="nav-link" data-scroll-target="#first-convergence-test"><span class="header-section-number">5.5</span> First Convergence Test</a></li>
  <li><a href="#robustness-improvements-to-mixed_ir" id="toc-robustness-improvements-to-mixed_ir" class="nav-link" data-scroll-target="#robustness-improvements-to-mixed_ir"><span class="header-section-number">5.6</span> Robustness Improvements to <code>mixed_ir</code></a>
  <ul class="collapse">
  <li><a href="#fp16fp64fp128-overflow-during-input-conversion" id="toc-fp16fp64fp128-overflow-during-input-conversion" class="nav-link" data-scroll-target="#fp16fp64fp128-overflow-during-input-conversion">1. FP16–FP64–FP128: overflow during input conversion</a></li>
  <li><a href="#fp32fp64fp128-divergence-of-iterative-refinement" id="toc-fp32fp64fp128-divergence-of-iterative-refinement" class="nav-link" data-scroll-target="#fp32fp64fp128-divergence-of-iterative-refinement">2. FP32–FP64–FP128: divergence of iterative refinement</a></li>
  <li><a href="#source-code-changes" id="toc-source-code-changes" class="nav-link" data-scroll-target="#source-code-changes">Source-Code Changes</a></li>
  <li><a href="#result" id="toc-result" class="nav-link" data-scroll-target="#result">Result</a></li>
  <li><a href="#fp16-residual-underflow-and-stagnation-problem" id="toc-fp16-residual-underflow-and-stagnation-problem" class="nav-link" data-scroll-target="#fp16-residual-underflow-and-stagnation-problem">FP16 residual underflow and stagnation problem</a></li>
  </ul></li>
  <li><a href="#plotting-convergence-experiments" id="toc-plotting-convergence-experiments" class="nav-link" data-scroll-target="#plotting-convergence-experiments"><span class="header-section-number">5.7</span> Plotting Convergence Experiments</a>
  <ul class="collapse">
  <li><a href="#expected-csv-format" id="toc-expected-csv-format" class="nav-link" data-scroll-target="#expected-csv-format">Expected CSV format</a></li>
  <li><a href="#generated-plots" id="toc-generated-plots" class="nav-link" data-scroll-target="#generated-plots">Generated plots</a></li>
  <li><a href="#logarithmic-plots-and-zero-values" id="toc-logarithmic-plots-and-zero-values" class="nav-link" data-scroll-target="#logarithmic-plots-and-zero-values">Logarithmic plots and zero values</a></li>
  <li><a href="#command-line-interface" id="toc-command-line-interface" class="nav-link" data-scroll-target="#command-line-interface">Command-line interface</a></li>
  <li><a href="#default-behavior" id="toc-default-behavior" class="nav-link" data-scroll-target="#default-behavior">Default behavior</a></li>
  <li><a href="#output-tags" id="toc-output-tags" class="nav-link" data-scroll-target="#output-tags">Output tags</a></li>
  <li><a href="#descriptive-plot-labels" id="toc-descriptive-plot-labels" class="nav-link" data-scroll-target="#descriptive-plot-labels">Descriptive plot labels</a></li>
  <li><a href="#matrix-family-examples" id="toc-matrix-family-examples" class="nav-link" data-scroll-target="#matrix-family-examples">Matrix-family examples</a></li>
  <li><a href="#encoding-the-solution-or-rhs-mode" id="toc-encoding-the-solution-or-rhs-mode" class="nav-link" data-scroll-target="#encoding-the-solution-or-rhs-mode">Encoding the solution or RHS mode</a></li>
  <li><a href="#examples-for-the-three-modes" id="toc-examples-for-the-three-modes" class="nav-link" data-scroll-target="#examples-for-the-three-modes">Examples for the three modes</a></li>
  <li><a href="#what-the-script-detects-automatically" id="toc-what-the-script-detects-automatically" class="nav-link" data-scroll-target="#what-the-script-detects-automatically">What the script detects automatically</a></li>
  <li><a href="#recording-metadata-inside-the-csv" id="toc-recording-metadata-inside-the-csv" class="nav-link" data-scroll-target="#recording-metadata-inside-the-csv">Recording metadata inside the CSV</a></li>
  <li><a href="#later-comparison-plots" id="toc-later-comparison-plots" class="nav-link" data-scroll-target="#later-comparison-plots">Later comparison plots</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/project_setup.html">Notes</a></li><li class="breadcrumb-item"><a href="../notes/experiments.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Implementing the Experiments &amp; Robustness Improvements</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Implementing the Experiments &amp; Robustness Improvements</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We want to plot the <strong>forward error</strong> and the <strong>backward error</strong> as function of the refinement step <span class="math inline">\(i\)</span>.</p>
<p>forward error:</p>
<p><span class="math display">\[
\text{forward error}_i = \frac{\norm{x_i - x_{\text{true}}}}{\norm{x_{\text{true}}}}
\]</span></p>
<p>Backward error:</p>
<p><span class="math display">\[
\eta_{i} = \frac{\norm{b - Ax_i}}{\norm{A}\norm{x_i} + \norm{b}}
\]</span></p>
<p>in <code>mixed_ir.hpp</code> the result struct currently only stores <code>rel_correction</code> vector, that records</p>
<p><span class="math display">\[
\frac{\norm{d_i}}{\norm{x_i}}
\]</span></p>
<p>We have to modify <code>mixed_ir</code> to store the iterates <span class="math inline">\(x_i\)</span>, so that we can compute forward and backward errors. We add the following member variable to the <code>MixedIRResult</code> struct:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">std::</span>vector<span class="op">&lt;</span>hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T_work<span class="op">&gt;&gt;</span> iterates<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We append the solutions to the iterates vector before the loop and after each loop iteration with the line:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="op">(</span>options<span class="op">.</span>store_iterates<span class="op">)</span> <span class="op">{</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    result<span class="op">.</span>iterates<span class="op">.</span>push_back<span class="op">(</span>result<span class="op">.</span>x<span class="op">);</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="temporary-matrix-generator" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="temporary-matrix-generator"><span class="header-section-number">5.1</span> Temporary Matrix Generator</h2>
<p>We start with a simple controlled family, a rotated SPD matrix:</p>
<p><span class="math display">\[
A = Q\Lambda Q^T
\]</span></p>
<p>where <span class="math inline">\(\Lambda\)</span> has eigenvalues <span class="math inline">\(1/\sqrt{\kappa} \dots \sqrt{\kappa}\)</span>. Then</p>
<p><span class="math display">\[
\kappa_2(A) = \kappa
\]</span></p>
<p>This family of matrices give a known true (exact) solution:</p>
<p><span class="math display">\[
x_{\text{true}} = (1, \dots, 1)^T
\]</span></p>
<p>So it can be used temporarily to test the pipeline.</p>
<p>The implementation is in</p>
<pre><code>code/include/test_matrices.hpp</code></pre>
</section>
<section id="matrix-generator-supervisor-version" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="matrix-generator-supervisor-version"><span class="header-section-number">5.2</span> Matrix Generator Supervisor Version</h2>
<p>The temporary generator constructs</p>
<p><span class="math display">\[
A = Q_{\text{block}}\Lambda Q_{\text{block}}^T
\]</span></p>
<p>where <span class="math inline">\(Q_{\text{block}}\)</span> consists only of independent <span class="math inline">\(2 \times 2\)</span> rotations. Consequently <span class="math inline">\(A\)</span> is block diagonal:</p>
<p><span class="math display">\[
A =
\begin{pmatrix}
A_1 &amp;        &amp;        &amp; 0 \\
    &amp; A_2    &amp;        &amp;   \\
    &amp;        &amp; \ddots &amp;   \\
0   &amp;        &amp;        &amp; A_m
\end{pmatrix},
\qquad
A_i \in \mathbb{R}^{2 \times 2}.
\]</span></p>
<p>Even though the entire block-diagonal matrix had condition number <span class="math inline">\(\kappa\)</span>, the individual <span class="math inline">\(2 \times 2\)</span> blocks is only approximately:</p>
<p><span class="math display">\[
\kappa^{1/(n-1)}
\]</span></p>
<p>Supervisors <code>randspd</code> constructs</p>
<p><span class="math display">\[
A = Q\Lambda Q^T
\]</span></p>
<p>where <span class="math inline">\(Q\)</span> is a dense random orthogonal matrix. Consequently, <span class="math inline">\(A\)</span> is generally dense, and every variable is coupled to every other variable, producing a genuinelly ill-conditioned system.</p>
<section id="nonsymmetric-generator" class="level3">
<h3 class="anchored" data-anchor-id="nonsymmetric-generator">Nonsymmetric Generator</h3>
<p>Iterative refinement with LU is not restricted to SPD matrices, so <code>randsvd</code> is also important. The wrapper</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">template</span><span class="op">&lt;</span><span class="kw">class</span> T<span class="op">&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>LinearSystem<span class="op">&lt;</span>T<span class="op">&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>make_random_svd_problem<span class="op">(</span><span class="bu">std::</span>size_t n<span class="op">,</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                        <span class="dt">double</span> kappa<span class="op">,</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                        <span class="dt">unsigned</span> <span class="dt">int</span> seed_u <span class="op">=</span> <span class="dv">42</span><span class="op">,</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                        <span class="dt">unsigned</span> <span class="dt">int</span> seed_v <span class="op">=</span> <span class="dv">137</span><span class="op">)</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>DenseMatrix<span class="op">&lt;</span>T<span class="op">&gt;</span> A<span class="op">(</span>n<span class="op">,</span> n<span class="op">);</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T<span class="op">&gt;</span> x_true<span class="op">(</span>n<span class="op">);</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T<span class="op">&gt;</span> b<span class="op">(</span>n<span class="op">);</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>randsvd<span class="op">(</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>        A<span class="op">,</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>        scalar_cast<span class="op">&lt;</span>T<span class="op">&gt;(</span>kappa<span class="op">),</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>        seed_u<span class="op">,</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        seed_v</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="op">);</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> <span class="op">(</span><span class="bu">std::</span>size_t i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> i <span class="op">&lt;</span> n<span class="op">;</span> <span class="op">++</span>i<span class="op">)</span> <span class="op">{</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>        x_true<span class="op">[</span>i<span class="op">]</span> <span class="op">=</span> T<span class="op">(</span><span class="dv">1</span><span class="op">);</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    A<span class="op">.</span>mv<span class="op">(</span>b<span class="op">,</span> x_true<span class="op">);</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> LinearSystem<span class="op">&lt;</span>T<span class="op">&gt;{</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>        A<span class="op">,</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>        b<span class="op">,</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>        x_true<span class="op">,</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>        kappa</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="op">};</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>produces</p>
<p><span class="math display">\[
A = U\Sigma V^T
\]</span></p>
<p>with singular values <span class="math inline">\(1, \dots 1/\kappa\)</span>. It is nonsymmetric and a more general test of the iterative LU algorithm.</p>
</section>
</section>
<section id="configurable-test-problem-construction" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="configurable-test-problem-construction"><span class="header-section-number">5.3</span> Configurable test-problem Construction</h2>
<p>The test-matrix infrastructure contained in ‘test_matrices.hpp’ supports three different ways of constructing the right-hand side <span class="math inline">\(b\)</span> and solution of</p>
<p><span class="math display">\[
Ax = b
\]</span></p>
<p>The matrix generator and the right-hand-side strategy are separated:</p>
<ol type="1">
<li>A matrix generator constructs <span class="math inline">\(A\)</span></li>
<li>A shared <code>complete_problem</code> function constructs <span class="math inline">\(b\)</span>.</li>
<li>The reference solution is computed in a separate, higher precision.</li>
</ol>
<section id="three-right-hand-side-modes" class="level3">
<h3 class="anchored" data-anchor-id="three-right-hand-side-modes">Three Right-hand-side Modes</h3>
<p>There are three availabe strategies represented by:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">enum</span> <span class="kw">class</span> RightHandSideMode <span class="op">{</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    ones_solution<span class="op">,</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    random_sign_solution<span class="op">,</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    random_normal_rhs</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="op">};</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><code>ones_solution</code>:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
x &amp;= (1, \dots, 1)^T \\
b &amp;= \text{fl}(Ax)
\end{aligned}
\]</span></p>
<ul>
<li><code>random_sign_solution</code>:</li>
</ul>
<p>Construct a reproducible random vector with</p>
<p><span class="math display">\[
x_i \in \{-1, 1\}
\]</span></p>
<p>and form</p>
<p><span class="math display">\[
b = \text{fl}(Ax)
\]</span></p>
<ul>
<li><code>random_normal_rhs</code>:</li>
</ul>
<p>Here we generate the right-hand-side <strong>directly</strong> (randomly):</p>
<p><span class="math display">\[
b_i \sim \mathcal{N}(0, 1)
\]</span></p>
<p>In all these cases the reference (true) solution is obtained by solving</p>
<p><span class="math display">\[
Ax_{\text{ref}} = b
\]</span></p>
<p>in a high precision (called measure or reference precision).</p>
</section>
<section id="test-problem-options" class="level3">
<h3 class="anchored" data-anchor-id="test-problem-options">Test-problem Options</h3>
<p>The choices and random sees are collected in:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">struct</span> TestProblemOptions <span class="op">{</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    RightHandSideMode rhs_mode <span class="op">=</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        RightHandSideMode<span class="op">::</span>ones_solution<span class="op">;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">unsigned</span> <span class="dt">int</span> matrix_seed_u <span class="op">=</span> <span class="dv">42</span><span class="op">;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="dt">unsigned</span> <span class="dt">int</span> matrix_seed_v <span class="op">=</span> <span class="dv">137</span><span class="op">;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="dt">unsigned</span> <span class="dt">int</span> vector_seed <span class="op">=</span> <span class="dv">2718</span><span class="op">;</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="dt">double</span> rotation_theta <span class="op">=</span> <span class="fl">0.3</span><span class="op">;</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="op">};</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><code>rhs_mode</code>: selects how <span class="math inline">\(b\)</span> is constructed</li>
<li><code>matrix_seed_u</code>: seed for the first random orthogonal matrix (used by <code>randspd</code>)</li>
<li><code>matrix_seed_v</code>: seed for the second random orthogonal matrix (used by <code>randsvd</code>)</li>
<li><code>vector_seed</code>: seed for the random-sign solution or random-normal right-hand side.</li>
<li><code>rotation_theta</code>: rotation angle used by the structured rotated-SPD generator.</li>
</ul>
<p>The default mode is <code>ones_solution</code>.</p>
</section>
<section id="linear-system-representation" class="level3">
<h3 class="anchored" data-anchor-id="linear-system-representation">Linear-system Representation</h3>
<p>The system stores the problem and reference solution (potentially in different precisions):</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">template</span><span class="op">&lt;</span><span class="kw">class</span> T_data<span class="op">,</span> <span class="kw">class</span> T_reference <span class="op">=</span> T_data<span class="op">&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="kw">struct</span> LinearSystem <span class="op">{</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>DenseMatrix<span class="op">&lt;</span>T_data<span class="op">&gt;</span> A<span class="op">;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T_data<span class="op">&gt;</span> b<span class="op">;</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T_reference<span class="op">&gt;</span> x_true<span class="op">;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="dt">double</span> kappa<span class="op">;</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="op">};</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><code>T_data</code>: the precision in which <span class="math inline">\(A\)</span> and <span class="math inline">\(b\)</span> are stored, normally <code>T_work</code>.</li>
<li><code>T_reference</code>: precision used for the reference solution, normally <code>T_measure</code>.</li>
</ul>
</section>
<section id="shared-complete_problem-function" class="level3">
<h3 class="anchored" data-anchor-id="shared-complete_problem-function">Shared <code>complete_problem</code> function</h3>
<p>We have three matrix generators,</p>
<ul>
<li><code>make_rotated_spd_problem</code></li>
<li><code>make_random_spd_problem</code></li>
<li><code>make_random_svd_problem</code></li>
</ul>
<p>each created only <span class="math inline">\(A\)</span> and delegates the remaining work to <code>create_problem</code>, the signature:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">template</span><span class="op">&lt;</span><span class="kw">class</span> T_data<span class="op">,</span> <span class="kw">class</span> T_reference<span class="op">&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>LinearSystem<span class="op">&lt;</span>T_data<span class="op">,</span> T_reference<span class="op">&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>complete_problem<span class="op">(</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    hdnum<span class="op">::</span>DenseMatrix<span class="op">&lt;</span>T_data<span class="op">&gt;</span> A<span class="op">,</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">double</span> kappa<span class="op">,</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">const</span> TestProblemOptions<span class="op">&amp;</span> options<span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The logical structure is:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="op">(</span>options<span class="op">.</span>rhs_mode <span class="op">==</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    RightHandSideMode<span class="op">::</span>ones_solution<span class="op">)</span> <span class="op">{</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">// Construct x = (1,...,1).</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">// Compute b = A*x in T_data.</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span> <span class="cf">if</span> <span class="op">(</span>options<span class="op">.</span>rhs_mode <span class="op">==</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>         RightHandSideMode<span class="op">::</span>random_sign_solution<span class="op">)</span> <span class="op">{</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">// Construct reproducible x_i in {-1,1}.</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">// Compute b = A*x in T_data.</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span> <span class="op">{</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">// Construct reproducible b_i ~ N(0,1)</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="co">// directly in T_data.</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>After <span class="math inline">\(b\)</span> is constructed the reference solution is computed:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">auto</span> x_reference <span class="op">=</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    high_precision_solve<span class="op">&lt;</span>T_reference<span class="op">&gt;(</span>A<span class="op">,</span> b<span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The reference solution is recomputed
</div>
</div>
<div class="callout-body-container callout-body">
<p>Even in the first two modes, even if we explicitly construct <span class="math inline">\(x\)</span>, we recompute</p>
<p><span class="math display">\[
x_{\text{true}} = \text{solve}_{\text{T}_{\text{ref}}}(A, b)
\]</span></p>
<p>because the matrix-vector product</p>
<p><span class="math display">\[
b = \text{fl}(Ax_{\text{constructed}})
\]</span></p>
<p>is founded. Therefore, the exact solution of the stored pair <span class="math inline">\((A, b)\)</span> can differ slightly from <span class="math inline">\(x_{\text{constructed}}\)</span>.</p>
</div>
</div>
</section>
<section id="high-precision-reference-solve" class="level3">
<h3 class="anchored" data-anchor-id="high-precision-reference-solve">High-precision reference solve</h3>
<p>The helper</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">template</span><span class="op">&lt;</span><span class="kw">class</span> T_reference<span class="op">,</span> <span class="kw">class</span> T_data<span class="op">&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T_reference<span class="op">&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>high_precision_solve<span class="op">(</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">const</span> hdnum<span class="op">::</span>DenseMatrix<span class="op">&lt;</span>T_data<span class="op">&gt;&amp;</span> A<span class="op">,</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">const</span> hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T_data<span class="op">&gt;&amp;</span> b<span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>contained in <code>reference_solve.hpp</code> computes a reference solution using hdnums LU-solver functions in <code>T_reference</code> precision.</p>
<p>For example, <code>T_reference = hdnum::FP256</code> provides a sufficiently accurate reference solution.</p>
</section>
<section id="matrix-generator-interfaces" class="level3">
<h3 class="anchored" data-anchor-id="matrix-generator-interfaces">Matrix-generator interfaces</h3>
<p>As mentioned there are three generators, all with compatible interfaces:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">template</span><span class="op">&lt;</span><span class="kw">class</span> T_data<span class="op">,</span> <span class="kw">class</span> T_reference <span class="op">=</span> T_data<span class="op">&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>LinearSystem<span class="op">&lt;</span>T_data<span class="op">,</span> T_reference<span class="op">&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>make_rotated_spd_problem<span class="op">(</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">std::</span>size_t n<span class="op">,</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">double</span> kappa<span class="op">,</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">const</span> TestProblemOptions<span class="op">&amp;</span> options <span class="op">=</span> <span class="op">{});</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb13"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">template</span><span class="op">&lt;</span><span class="kw">class</span> T_data<span class="op">,</span> <span class="kw">class</span> T_reference <span class="op">=</span> T_data<span class="op">&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>LinearSystem<span class="op">&lt;</span>T_data<span class="op">,</span> T_reference<span class="op">&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>make_random_spd_problem<span class="op">(</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">std::</span>size_t n<span class="op">,</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">double</span> kappa<span class="op">,</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">const</span> TestProblemOptions<span class="op">&amp;</span> options <span class="op">=</span> <span class="op">{});</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb14"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">template</span><span class="op">&lt;</span><span class="kw">class</span> T_data<span class="op">,</span> <span class="kw">class</span> T_reference <span class="op">=</span> T_data<span class="op">&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>LinearSystem<span class="op">&lt;</span>T_data<span class="op">,</span> T_reference<span class="op">&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>make_random_svd_problem<span class="op">(</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">std::</span>size_t n<span class="op">,</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">double</span> kappa<span class="op">,</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">const</span> TestProblemOptions<span class="op">&amp;</span> options <span class="op">=</span> <span class="op">{});</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Each generator</p>
<ol type="1">
<li>constructs its particular matrix <span class="math inline">\(A\)</span></li>
<li>calls <code>complete_problem</code></li>
<li>returns <code>LinearSystem&lt;T_data, T_reference&gt;</code> struct.</li>
</ol>
<p>Which enables plugging in different matrix families in an experiment.</p>
</section>
<section id="usage-examples" class="level3">
<h3 class="anchored" data-anchor-id="usage-examples">Usage Examples</h3>
<p>Define the precisions:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">using</span> T_work <span class="op">=</span> hdnum<span class="op">::</span>FP64<span class="op">;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="kw">using</span> T_measure <span class="op">=</span> hdnum<span class="op">::</span>FP256<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>all-ones <span class="math inline">\(x\)</span>:</li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mpir<span class="op">::</span>TestProblemOptions problem_options<span class="op">;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>problem_options<span class="op">.</span>rhs_mode <span class="op">=</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    mpir<span class="op">::</span>RightHandSideMode<span class="op">::</span>ones_solution<span class="op">;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="kw">auto</span> problem <span class="op">=</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    mpir<span class="op">::</span>make_random_spd_problem<span class="op">&lt;</span>T_work<span class="op">,</span> T_measure<span class="op">&gt;(</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>        n<span class="op">,</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>        kappa<span class="op">,</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>        problem_options</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>random-sign ones <span class="math inline">\(x\)</span>:</li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mpir<span class="op">::</span>TestProblemOptions problem_options<span class="op">;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>problem_options<span class="op">.</span>rhs_mode <span class="op">=</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    mpir<span class="op">::</span>RightHandSideMode<span class="op">::</span>random_sign_solution<span class="op">;</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>problem_options<span class="op">.</span>vector_seed <span class="op">=</span> <span class="dv">2718</span><span class="op">;</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="kw">auto</span> problem <span class="op">=</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    mpir<span class="op">::</span>make_random_spd_problem<span class="op">&lt;</span>T_work<span class="op">,</span> T_measure<span class="op">&gt;(</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>        n<span class="op">,</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>        kappa<span class="op">,</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>        problem_options</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>random-normal <span class="math inline">\(b\)</span>:</li>
</ul>
<div class="sourceCode" id="cb18"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mpir<span class="op">::</span>TestProblemOptions problem_options<span class="op">;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>problem_options<span class="op">.</span>rhs_mode <span class="op">=</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    mpir<span class="op">::</span>RightHandSideMode<span class="op">::</span>random_normal_rhs<span class="op">;</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>problem_options<span class="op">.</span>vector_seed <span class="op">=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="kw">auto</span> problem <span class="op">=</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    mpir<span class="op">::</span>make_random_svd_problem<span class="op">&lt;</span>T_work<span class="op">,</span> T_measure<span class="op">&gt;(</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        n<span class="op">,</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>        kappa<span class="op">,</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>        problem_options</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>only the generator call needs to change, the resulting problems are used identically:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">auto</span> result <span class="op">=</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    mpir<span class="op">::</span>mixed_ir<span class="op">&lt;</span>T_factor<span class="op">,</span> T_work<span class="op">,</span> T_residual<span class="op">&gt;(</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>        problem<span class="op">.</span>A<span class="op">,</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>        problem<span class="op">.</span>b<span class="op">,</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        ir_options</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="error-metrics-helper" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="error-metrics-helper"><span class="header-section-number">5.4</span> Error Metrics Helper</h2>
<p>We implement functions to compute</p>
<ul>
<li><span class="math inline">\(\normsub{\cdot}{\infty}\)</span> for matrices and vectors,</li>
<li>relative forward error with the infinity norm</li>
<li>relative backward error with the inifinity norm</li>
</ul>
<p>contained in the file</p>
<pre><code>code/include/error_metrics.hpp</code></pre>
</section>
<section id="first-convergence-test" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="first-convergence-test"><span class="header-section-number">5.5</span> First Convergence Test</h2>
<p>We test our pipeline with a first test that uses the precision tripple:</p>
<ul>
<li><span class="math inline">\(u_f\)</span> : FP16</li>
<li><span class="math inline">\(u\)</span>: FP64</li>
<li><span class="math inline">\(u_r\)</span>: FP128</li>
</ul>
<p>For matrices of size <span class="math inline">\(100 \times 100\)</span> with <span class="math inline">\(\kappa\)</span> values: <span class="math inline">\(1, 10, 100, 1000, 10000\)</span>.</p>
<p>The test writes for each matrix the convergence history to csv file. Specifically it writes the values:</p>
<ul>
<li>kappa,</li>
<li>iteration,</li>
<li>relative forward error</li>
<li>relative backward error</li>
<li>relative correction</li>
</ul>
<p>in a single lines for each iteration step, for each matrix. This gives us the convergence histories.</p>
<p>It is implemented in the file</p>
<pre><code>code/experiments/exp_convergence.cc</code></pre>
<p>Following was the result of the experiment:</p>
<pre class="csv"><code>kappa,iteration,forward_error_inf,backward_error_inf,rel_correction
1,0,0,0,0
1,1,0,0,0
10,0,0.000976562,0.000441793,0
10,1,9.53674e-07,4.31651e-07,0.00047591
10,2,5.96046e-08,5.1214e-09,3.1641e-07
10,3,5.96046e-08,5.1214e-09,1.68587e-08
10,4,5.96046e-08,5.1214e-09,1.68587e-08
10,5,5.96046e-08,5.1214e-09,1.68587e-08
10,6,5.96046e-08,5.1214e-09,1.68587e-08
10,7,5.96046e-08,5.1214e-09,1.68587e-08
10,8,5.96046e-08,5.1214e-09,1.68587e-08
10,9,5.96046e-08,5.1214e-09,1.68587e-08
10,10,5.96046e-08,5.1214e-09,1.68587e-08
10,11,5.96046e-08,5.1214e-09,1.68587e-08
10,12,5.96046e-08,5.1214e-09,1.68587e-08
10,13,5.96046e-08,5.1214e-09,1.68587e-08
10,14,5.96046e-08,5.1214e-09,1.68587e-08
10,15,5.96046e-08,5.1214e-09,1.68587e-08
10,16,5.96046e-08,5.1214e-09,1.68587e-08
10,17,5.96046e-08,5.1214e-09,1.68587e-08
10,18,5.96046e-08,5.1214e-09,1.68587e-08
10,19,5.96046e-08,5.1214e-09,1.68587e-08
10,20,5.96046e-08,5.1214e-09,1.68587e-08
100,0,0.000976562,0.000481752,0
100,1,9.53674e-07,4.70694e-07,0.000444832
100,2,1.78814e-07,1.42242e-09,2.52178e-07
100,3,1.78814e-07,1.42242e-09,0
1000,0,0.000976562,0.000460731,0
1000,1,9.53674e-07,3.07722e-07,0.000591975
1000,2,8.9407e-07,6.88472e-10,4.02364e-07
1000,3,8.9407e-07,5.65293e-10,1.3328e-08
1000,4,8.9407e-07,5.65293e-10,1.19209e-08
1000,5,8.9407e-07,5.65293e-10,1.19209e-08
1000,6,8.9407e-07,5.65293e-10,1.19209e-08
1000,7,8.9407e-07,5.65293e-10,1.19209e-08
1000,8,8.9407e-07,5.65293e-10,1.19209e-08
1000,9,8.9407e-07,5.65293e-10,1.19209e-08
1000,10,8.9407e-07,5.65293e-10,1.19209e-08
1000,11,8.9407e-07,5.65293e-10,1.19209e-08
1000,12,8.9407e-07,5.65293e-10,1.19209e-08
1000,13,8.9407e-07,5.65293e-10,1.19209e-08
1000,14,8.9407e-07,5.65293e-10,1.19209e-08
1000,15,8.9407e-07,5.65293e-10,1.19209e-08
1000,16,8.9407e-07,5.65293e-10,1.19209e-08
1000,17,8.9407e-07,5.65293e-10,1.19209e-08
1000,18,8.9407e-07,5.65293e-10,1.19209e-08
1000,19,8.9407e-07,5.65293e-10,1.19209e-08
1000,20,8.9407e-07,5.65293e-10,1.19209e-08
10000,0,0.000976562,0.000375237,0
10000,1,3.33786e-06,4.73515e-08,0.000488379
10000,2,9.53674e-07,3.8223e-10,5.28939e-07
10000,3,9.53674e-07,1.29324e-10,1.03238e-08
10000,4,9.53674e-07,1.29324e-10,0</code></pre>
</section>
<section id="robustness-improvements-to-mixed_ir" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="robustness-improvements-to-mixed_ir"><span class="header-section-number">5.6</span> Robustness Improvements to <code>mixed_ir</code></h2>
<p>We encountered two failures at <span class="math inline">\(\kappa(A)=10^9\)</span>. Both caused a floating-point exception, but for different reasons.</p>
<section id="fp16fp64fp128-overflow-during-input-conversion" class="level3">
<h3 class="anchored" data-anchor-id="fp16fp64fp128-overflow-during-input-conversion">1. FP16–FP64–FP128: overflow during input conversion</h3>
<section id="problem" class="level4">
<h4 class="anchored" data-anchor-id="problem">Problem</h4>
<p>We converted <span class="math inline">\(A\)</span> and <span class="math inline">\(b\)</span> from FP64 to the FP16 factorization precision. FP16 has a maximum finite value of approximately</p>
<p><span class="math display">\[
65504.
\]</span></p>
<p>Some entries exceeded this limit. The converted data therefore contained non-finite values. LU factorization and the initial solve propagated these values into <span class="math inline">\(x_0\)</span>.</p>
<p>The program crashed when <code>compute_residual</code> attempted to convert the non-finite iterate to the GMP-backed FP128 type. This type cannot represent <code>NaN</code> or infinity.</p>
</section>
<section id="detection" class="level4">
<h4 class="anchored" data-anchor-id="detection">Detection</h4>
<p>The GDB backtrace located the crash in the GMP conversion performed by <code>compute_residual</code>.</p>
<p>We traced the invalid values backward:</p>
<p><span class="math display">\[
A_f,b_f
\longrightarrow LU_f
\longrightarrow x_{0,f}
\longrightarrow x_0
\longrightarrow \text{GMP conversion}.
\]</span></p>
<p>Inspection showed that the first non-finite values appeared during conversion to FP16.</p>
<p>The bfloat16 experiment supported this conclusion. Bfloat16 has a wider exponent range and did not overflow at the same point.</p>
</section>
<section id="solution" class="level4">
<h4 class="anchored" data-anchor-id="solution">Solution</h4>
<p>We chose to detect the overflow and terminate safely. We did not implement scaling or equilibration.</p>
<p>The algorithm now terminates with <code>factorization_input_non_finite</code> if <span class="math inline">\(A_f\)</span> or <span class="math inline">\(b_f\)</span> contains a non-finite value.</p>
<p>Scaling could prevent this specific overflow, but it would not change <span class="math inline">\(\kappa(A)\)</span>. It would therefore not make FP16 iterative refinement reliable at <span class="math inline">\(\kappa(A)=10^9\)</span>.</p>
<hr>
</section>
</section>
<section id="fp32fp64fp128-divergence-of-iterative-refinement" class="level3">
<h3 class="anchored" data-anchor-id="fp32fp64fp128-divergence-of-iterative-refinement">2. FP32–FP64–FP128: divergence of iterative refinement</h3>
<section id="problem-1" class="level4">
<h4 class="anchored" data-anchor-id="problem-1">Problem</h4>
<p>FP32 could represent the matrix entries, so the initial conversion succeeded. The refinement process nevertheless diverged because</p>
<p><span class="math display">\[
\kappa(A)u_f
\approx 10^9\cdot 6\times 10^{-8}
\approx 60&gt;1.
\]</span></p>
<p>The absolute correction norms grew by a factor of approximately <span class="math inline">\(36\)</span> per iteration.</p>
<p>The existing stopping quantity,</p>
<p><span class="math display">\[
\frac{\lVert d_k\rVert_2}{\lVert x_k\rVert_2},
\]</span></p>
<p>did not detect this behavior. Both <span class="math inline">\(d_k\)</span> and <span class="math inline">\(x_k\)</span> grew at similar rates, so the ratio remained approximately constant at <span class="math inline">\(37.29\)</span>.</p>
<p>Without additional checks, the growth eventually produced non-finite values and another unsafe conversion to FP128.</p>
</section>
<section id="detection-1" class="level4">
<h4 class="anchored" data-anchor-id="detection-1">Detection</h4>
<p>We examined the ratio of consecutive correction norms:</p>
<p><span class="math display">\[
\frac{\lVert d_k\rVert_2}
     {\lVert d_{k-1}\rVert_2}
\approx 36.
\]</span></p>
<p>This showed persistent, rapid growth. We therefore decided to monitor absolute correction norms instead of relying only on relative corrections.</p>
</section>
<section id="solution-1" class="level4">
<h4 class="anchored" data-anchor-id="solution-1">Solution</h4>
<p>We added a divergence detector based on</p>
<p><span class="math display">\[
\lVert d_k\rVert_2
&gt;
\gamma\lVert d_{k-1}\rVert_2.
\]</span></p>
<p>The default parameters are</p>
<p><span class="math display">\[
\gamma=10,
\qquad
\text{required growth steps}=3.
\]</span></p>
<p>The algorithm reports divergence after three consecutive excessive-growth comparisons. It rejects the correction that triggers termination and preserves the last accepted iterate.</p>
</section>
</section>
<section id="source-code-changes" class="level3">
<h3 class="anchored" data-anchor-id="source-code-changes">Source-Code Changes</h3>
<section id="termination-statuses" class="level4">
<h4 class="anchored" data-anchor-id="termination-statuses">Termination statuses</h4>
<p>We introduced statuses that distinguish the main outcomes:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">enum</span> <span class="kw">class</span> MixedIRStatus <span class="op">{</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    converged<span class="op">,</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    max_iterations<span class="op">,</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    factorization_input_non_finite<span class="op">,</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    non_finite<span class="op">,</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    diverged</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="op">};</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>These represent:</p>
<ul>
<li>successful convergence;</li>
<li>reaching the iteration limit;</li>
<li>non-finite factorization input;</li>
<li>a non-finite value produced later;</li>
<li>detected divergence.</li>
</ul>
</section>
<section id="finite-value-checks" class="level4">
<h4 class="anchored" data-anchor-id="finite-value-checks">Finite-value checks</h4>
<p>We added <code>all_finite</code> helpers for vectors and matrices.</p>
<p>IEEE-like types and CPFloat values are checked with <code>std::isfinite</code>. GMP-backed <code>hdnum::FP&lt;m&gt;</code> values require separate handling because they cannot represent <code>NaN</code> or infinity.</p>
<p>The main rule is:</p>
<blockquote class="blockquote">
<p>Check IEEE-like values before converting them to a GMP-backed type.</p>
</blockquote>
<p>We kept all checks inside <code>mixed_ir</code>. We did not modify HDNUM, <code>lowprec_cpfloat.hh</code>, <code>compute_residual</code>, or the triangular solvers.</p>
</section>
<section id="guard-placement" class="level4">
<h4 class="anchored" data-anchor-id="guard-placement">Guard placement</h4>
<p>We added finite-value checks at the following points:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Location</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>After converting <span class="math inline">\(A,b\)</span> to <span class="math inline">\(A_f,b_f\)</span></td>
<td>Detect factorization-input overflow</td>
</tr>
<tr class="even">
<td>After the initial solve</td>
<td>Detect an invalid initial solution</td>
</tr>
<tr class="odd">
<td>After converting <span class="math inline">\(x_{0,f}\)</span> to working precision</td>
<td>Validate the initial iterate</td>
</tr>
<tr class="even">
<td>Before <code>compute_residual</code></td>
<td>Protect the GMP conversion</td>
</tr>
<tr class="odd">
<td>After computing <span class="math inline">\(r_r\)</span></td>
<td>Support generic residual types</td>
</tr>
<tr class="even">
<td>After converting <span class="math inline">\(r_r\)</span> to <span class="math inline">\(r_f\)</span></td>
<td>Detect narrowing overflow</td>
</tr>
<tr class="odd">
<td>After solving for <span class="math inline">\(d_f\)</span></td>
<td>Detect an invalid correction</td>
</tr>
<tr class="even">
<td>After converting <span class="math inline">\(d_f\)</span> to <span class="math inline">\(d_w\)</span></td>
<td>Validate the working-precision correction</td>
</tr>
<tr class="odd">
<td>After converting the relative correction to <code>double</code></td>
<td>Detect norm or conversion overflow</td>
</tr>
<tr class="even">
<td>After forming <span class="math inline">\(x_{k+1}\)</span></td>
<td>Detect overflow during the update</td>
</tr>
</tbody>
</table>
<p>We now form the new iterate as a candidate:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T_work<span class="op">&gt;</span> x_next<span class="op">(</span>result<span class="op">.</span>x<span class="op">);</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> <span class="op">(</span><span class="bu">std::</span>size_t i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> i <span class="op">&lt;</span> n<span class="op">;</span> <span class="op">++</span>i<span class="op">)</span> <span class="op">{</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    x_next<span class="op">[</span>i<span class="op">]</span> <span class="op">+=</span> d_w<span class="op">[</span>i<span class="op">];</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="op">(!</span>all_finite<span class="op">(</span>x_next<span class="op">))</span> <span class="op">{</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    result<span class="op">.</span>status <span class="op">=</span> MixedIRStatus<span class="op">::</span>non_finite<span class="op">;</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> result<span class="op">;</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>result<span class="op">.</span>x <span class="op">=</span> x_next<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This preserves the last valid iterate if the update fails. We increment <code>result.iterations</code> only after accepting the update.</p>
</section>
<section id="divergence-options" class="level4">
<h4 class="anchored" data-anchor-id="divergence-options">Divergence options</h4>
<p>We added three options:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="dt">bool</span> detect_divergence <span class="op">=</span> <span class="kw">true</span><span class="op">;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>T_work divergence_growth_factor <span class="op">=</span> T_work<span class="op">(</span><span class="dv">10</span><span class="op">);</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="bu">std::</span>size_t divergence_growth_steps <span class="op">=</span> <span class="dv">3</span><span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>They control:</p>
<ul>
<li>whether divergence detection is enabled;</li>
<li>the minimum excessive-growth factor;</li>
<li>the required number of consecutive growth steps.</li>
</ul>
<p>Valid user-supplied values should satisfy:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>divergence_growth_factor <span class="op">&gt;</span> T_work<span class="op">(</span><span class="dv">1</span><span class="op">)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>divergence_growth_steps <span class="op">&gt;</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="correction-norm-history" class="level4">
<h4 class="anchored" data-anchor-id="correction-norm-history">Correction-norm history</h4>
<p>We added diagnostic storage to <code>MixedIRResult</code>:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="bu">std::</span>vector<span class="op">&lt;</span><span class="dt">double</span><span class="op">&gt;</span> correction_norms<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>It stores each finite value of <span class="math inline">\(\lVert d_k\rVert_2\)</span>.</p>
<p>The history also includes a correction that triggers divergence but is not applied. We store the norms even when divergence detection is disabled.</p>
</section>
<section id="detector-state-and-comparison" class="level4">
<h4 class="anchored" data-anchor-id="detector-state-and-comparison">Detector state and comparison</h4>
<p>Before the refinement loop, we introduced:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>T_work previous_correction_norm <span class="op">=</span> T_work<span class="op">(</span><span class="dv">0</span><span class="op">);</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="dt">bool</span> have_previous_correction_norm <span class="op">=</span> <span class="kw">false</span><span class="op">;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="bu">std::</span>size_t consecutive_growth_steps <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>After computing and validating <span class="math inline">\(d_w\)</span>, we calculate:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="at">const</span> T_work correction_norm_w <span class="op">=</span> hdnum<span class="op">::</span>norm<span class="op">(</span>d_w<span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We then test for excessive growth:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="at">const</span> <span class="dt">bool</span> excessive_growth <span class="op">=</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    previous_correction_norm <span class="op">&gt;</span> T_work<span class="op">(</span><span class="dv">0</span><span class="op">)</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="op">&amp;&amp;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    correction_norm_w</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>        <span class="op">&gt;</span> options<span class="op">.</span>divergence_growth_factor</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>            <span class="op">*</span> previous_correction_norm<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Excessive growth increments the counter. Any other result resets it. Once the counter reaches the configured limit, the algorithm returns</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>result<span class="op">.</span>status <span class="op">=</span> MixedIRStatus<span class="op">::</span>diverged<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>before applying the correction.</p>
</section>
</section>
<section id="result" class="level3">
<h3 class="anchored" data-anchor-id="result">Result</h3>
<p>With divergence detection enabled, the FP32–FP64–FP128 experiment terminates early with <code>diverged</code>.</p>
<p>With divergence detection disabled, the finite-value guards still prevent a crash. In our test, the algorithm completed 19 updates before detecting a non-finite value:</p>
<pre class="text"><code>kappa = 1e+09
converged = 0
iterations = 19
final_rel_correction = 37.2908</code></pre>
<p>The two safeguards have separate roles:</p>
<ul>
<li>The divergence detector stops persistent growth early.</li>
<li>The finite-value checks prevent unsafe operations and crashes.</li>
</ul>
</section>
<section id="fp16-residual-underflow-and-stagnation-problem" class="level3">
<h3 class="anchored" data-anchor-id="fp16-residual-underflow-and-stagnation-problem">FP16 residual underflow and stagnation problem</h3>
<p>We tested three-precision iterative refinement with</p>
<p><span class="math display">\[
T_{\mathrm{factor}}=\mathrm{FP16},\qquad
T_{\mathrm{work}}=\mathrm{FP64},\qquad
T_{\mathrm{residual}}=\mathrm{FP128}.
\]</span></p>
<p>The LU factorization and correction solve used FP16. Iterates were stored and updated in FP64. Residuals were computed in FP128.</p>
<p>For <span class="math inline">\(n=100\)</span>, the convergence sweep produced unexpected results:</p>
<ul>
<li><p>For <span class="math inline">\(\kappa=10\)</span>, the method did not converge after 20 iterations. The forward error stagnated near <span class="math inline">\(5.96\times10^{-8}\)</span>, and the relative correction stagnated near <span class="math inline">\(1.69\times10^{-8}\)</span>.</p></li>
<li><p>For <span class="math inline">\(\kappa=100\)</span>, the method appeared to converge after only three iterations because the computed correction became exactly zero.</p></li>
<li><p>Similar nonmonotone behavior occurred for larger condition numbers.</p></li>
</ul>
<p>This was inconsistent with the usual refinement condition. Since</p>
<p><span class="math display">\[
u_{\mathrm{FP16}}=2^{-11}\approx4.88\times10^{-4},
\]</span></p>
<p>we have, for <span class="math inline">\(\kappa=10\)</span>,</p>
<p><span class="math display">\[
\kappa u_{\mathrm{FP16}}
\approx4.88\times10^{-3}\ll1.
\]</span></p>
<p>The <span class="math inline">\(\kappa=10\)</span> problem should therefore have been favorable for iterative refinement.</p>
<p>The repeated values</p>
<p><span class="math display">\[
5.96046\times10^{-8}
\quad\text{and}\quad
1.19209\times10^{-7}
\]</span></p>
<p>were an important clue. These are respectively the smallest positive FP16 subnormal number and twice that number.</p>
<section id="empirical-diagnosis" class="level4">
<h4 class="anchored" data-anchor-id="empirical-diagnosis">Empirical diagnosis</h4>
<section id="comparison-with-bfloat16" class="level5">
<h5 class="anchored" data-anchor-id="comparison-with-bfloat16">Comparison with bfloat16</h5>
<p>We replaced FP16 with bfloat16. Bfloat16 has fewer significand bits than FP16 but a much larger exponent range.</p>
<p>The relevant results were:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\kappa\)</span></th>
<th style="text-align: center;">Converged</th>
<th style="text-align: right;">Iterations</th>
<th style="text-align: right;">Final relative correction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"><span class="math inline">\(5.07389\times10^{-17}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;"><span class="math inline">\(4.71855\times10^{-17}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;"><span class="math inline">\(6.68688\times10^{-15}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">1000</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;"><span class="math inline">\(2.24847\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">10000</td>
<td style="text-align: center;">No</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;"><span class="math inline">\(12.5079\)</span></td>
</tr>
</tbody>
</table>
<p>In particular, bfloat16 converged for <span class="math inline">\(\kappa=10\)</span>, while FP16 did not. Because bfloat16 has lower precision but greater range, this supported the hypothesis that the FP16 failure was caused by its restricted exponent range, not by insufficient significand precision alone.</p>
</section>
<section id="conceptual-hypothesis" class="level5">
<h5 class="anchored" data-anchor-id="conceptual-hypothesis">Conceptual hypothesis</h5>
<p>At iteration <span class="math inline">\(k\)</span>, the residual is computed accurately in FP128:</p>
<p><span class="math display">\[
r_k=b-Ax_k.
\]</span></p>
<p>The original implementation then converted it directly to FP16:</p>
<p><span class="math display">\[
r_k^{(128)}
\longrightarrow
r_k^{(16)}.
\]</span></p>
<p>For FP16,</p>
<p><span class="math display">\[
x_{\min,\mathrm{normal}}
=
2^{-14}
\approx6.1035\times10^{-5},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
x_{\min,\mathrm{subnormal}}
=
2^{-24}
\approx5.9605\times10^{-8}.
\]</span></p>
<p>Under round-to-nearest, values below approximately</p>
<p><span class="math display">\[
2^{-25}\approx2.9802\times10^{-8}
\]</span></p>
<p>round to zero.</p>
<p>We therefore hypothesized that, as refinement reduced the residual:</p>
<ol type="1">
<li><p>Some FP128 residual components became zero when converted to FP16.</p></li>
<li><p>Surviving components were rounded to a small number of FP16 subnormal values.</p></li>
<li><p>The FP16 correction solve received an increasingly inaccurate right-hand side.</p></li>
<li><p>The correction eventually stagnated or became exactly zero.</p></li>
</ol>
<p>An exactly zero correction could also cause false convergence because the relative-correction stopping criterion would evaluate to zero.</p>
</section>
<section id="diagnostic-implementation" class="level5">
<h5 class="anchored" data-anchor-id="diagnostic-implementation">Diagnostic implementation</h5>
<p>We added per-iteration residual-conversion diagnostics to <code>mixed_ir</code>:</p>
<ul>
<li><p><span class="math inline">\(\lVert r_k\rVert_\infty\)</span>, computed in residual precision;</p></li>
<li><p>the smallest nonzero component of <span class="math inline">\(r_k\)</span>;</p></li>
<li><p>the number of nonzero FP128 residual components;</p></li>
<li><p>the number of nonzero components that became exactly zero during FP128-to-FP16 conversion.</p></li>
</ul>
<p>The important distinction was:</p>
<ul>
<li><p><code>nonzero_components</code> described the original FP128 residual;</p></li>
<li><p><code>zeroed_by_conversion</code> described information lost in the FP16 copy.</p></li>
</ul>
<p>Thus,</p>
<pre class="text"><code>nonzero_components = 100
zeroed_by_conversion = 20</code></pre>
<p>meant that all 100 components were nonzero in FP128, but only 80 remained nonzero after conversion to FP16.</p>
</section>
<section id="diagnostic-experiment" class="level5">
<h5 class="anchored" data-anchor-id="diagnostic-experiment">Diagnostic experiment</h5>
<p>We tested one fixed random symmetric positive-definite system with</p>
<p><span class="math display">\[
n=100,qquad \kappa(A)=10,
\]</span></p>
<p>using FP16–FP64–FP128 refinement.</p>
<p>The initial diagnostic results were:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Iteration</th>
<th style="text-align: right;"><span class="math inline">\(\lVert r_k\rVert_\infty\)</span></th>
<th style="text-align: right;">Smallest nonzero component</th>
<th style="text-align: right;">Zeroed by FP16 conversion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(1.3474\times10^{-2}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.3279\times10^{-5}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;"><span class="math inline">\(5.4754\times10^{-5}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.4203\times10^{-8}\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;"><span class="math inline">\(4.8336\times10^{-7}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(3.0833\times10^{-9}\)</span></td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;"><span class="math inline">\(4.1084\times10^{-7}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2.0158\times10^{-9}\)</span></td>
<td style="text-align: right;">20</td>
</tr>
</tbody>
</table>
<p>The first two refinement steps reduced the residual substantially:</p>
<p><span class="math display">\[
\frac{\lVert r_0\rVert_\infty}
     {\lVert r_1\rVert_\infty}
\approx246,
\qquad
\frac{\lVert r_1\rVert_\infty}
     {\lVert r_2\rVert_\infty}
\approx113.
\]</span></p>
<p>At iteration 2, residual components first became zero during conversion. At essentially the same point, residual reduction stopped.</p>
<p>For <span class="math inline">\(k\ge2\)</span>,</p>
<p><span class="math display">\[
2.97\times10^{-7}
\le
\lVert r_k\rVert_\infty
\le
5.00\times10^{-7},
\]</span></p>
<p>with mean approximately</p>
<p><span class="math display">\[
4.17\times10^{-7}.
\]</span></p>
<p>Between 9 and 20 components were lost per iteration, with an average of approximately 14.5.</p>
<p>Even before components became zero, conversion was already inaccurate. At iteration 1, the smallest component was</p>
<p><span class="math display">\[
3.4203\times10^{-8}.
\]</span></p>
<p>It was above the rounding-to-zero threshold but below the smallest FP16 subnormal, so it was rounded to approximately</p>
<p><span class="math display">\[
5.9605\times10^{-8}.
\]</span></p>
<p>Therefore, <code>zeroed_by_conversion = 0</code> did not imply an accurate conversion.</p>
<p>After iteration 2, the entire residual was only several FP16 subnormal increments away from zero. The residual was consequently represented by a very small set of possible FP16 values. This produced severe quantization even for components that remained nonzero.</p>
<p>The experiment confirmed the hypothesis:</p>
<blockquote class="blockquote">
<p>The FP128 residual remained fully nonzero, but conversion to unscaled FP16 discarded or severely quantized its components. This information loss began at the same point as residual stagnation.</p>
</blockquote>
</section>
</section>
<section id="implemented-solution" class="level4">
<h4 class="anchored" data-anchor-id="implemented-solution">Implemented solution</h4>
<section id="conceptual-solution" class="level5">
<h5 class="anchored" data-anchor-id="conceptual-solution">Conceptual solution</h5>
<p>We introduced infinity-norm residual scaling:</p>
<p><span class="math display">\[
\theta_k=\lVert r_k\rVert_\infty,
\qquad
\widehat r_k=\frac{r_k}{\theta_k}.
\]</span></p>
<p>Instead of solving directly with the small residual, we solve</p>
<p><span class="math display">\[
A\widehat d_k=\widehat r_k
\]</span></p>
<p>in factor precision and then recover the actual correction:</p>
<p><span class="math display">\[
d_k=\theta_k\widehat d_k.
\]</span></p>
<p>In exact arithmetic, this is equivalent to</p>
<p><span class="math display">\[
Ad_k=r_k.
\]</span></p>
<p>The normalization ensures</p>
<p><span class="math display">\[
\lVert\widehat r_k\rVert_\infty=1.
\]</span></p>
<p>The residual conversion therefore uses the available FP16 range effectively rather than placing the entire vector near zero.</p>
<p>Scaling does not increase FP16 precision. It removes the irrelevant absolute magnitude of the residual before conversion.</p>
</section>
<section id="implementation-in-mixed_ir" class="level5">
<h5 class="anchored" data-anchor-id="implementation-in-mixed_ir">Implementation in <code>mixed_ir</code></h5>
<p>We added an optional setting:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="dt">bool</span> scale_residual <span class="op">=</span> <span class="kw">false</span><span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The default preserves the original algorithm.</p>
<p>When scaling is enabled, the implementation:</p>
<ol type="1">
<li><p>Computes <span class="math inline">\(\lVert r_k\rVert_\infty\)</span> in <code>T_residual</code>.</p></li>
<li><p>Preserves the original residual <code>r_r</code> for diagnostics.</p></li>
<li><p>Creates a separate correction right-hand side:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>hdnum<span class="op">::</span>Vector<span class="op">&lt;</span>T_residual<span class="op">&gt;</span> correction_rhs_r<span class="op">(</span>r_r<span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>Normalizes it when the residual is nonzero:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>correction_rhs_r<span class="op">[</span>i<span class="op">]</span> <span class="op">=</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    correction_rhs_r<span class="op">[</span>i<span class="op">]</span> <span class="op">/</span> residual_scale_r<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>Converts the normalized vector, rather than the original residual, to factor precision:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>convert<span class="op">(</span>r_f<span class="op">,</span> correction_rhs_r<span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>Performs the existing FP16 LU solve without changing the factors or solve routine.</p></li>
<li><p>Converts the normalized correction to working precision.</p></li>
<li><p>Rescales it in FP64:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>d_w<span class="op">[</span>i<span class="op">]</span> <span class="op">=</span> residual_scale_w <span class="op">*</span> d_w<span class="op">[</span>i<span class="op">];</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p>Performs the original update:</p>
<p><span class="math display">\[
x_{k+1}=x_k+d_k.
\]</span></p></li>
</ol>
<p>The scale is applied in working precision, not factor precision. Thus, the small value <span class="math inline">\(\theta_k\)</span> never needs to be represented in FP16.</p>
<p>The zero-residual case skips normalization, preventing division by zero. We also retained the existing finite-value checks after rescaling.</p>
<p>The diagnostic semantics were updated accordingly:</p>
<ul>
<li><p>residual magnitudes still describe the original <span class="math inline">\(r_k\)</span>;</p></li>
<li><p><code>zeroed_by_conversion</code> describes conversion of the actual correction right-hand side:</p>
<ul>
<li><p><span class="math inline">\(r_k\)</span> in unscaled mode;</p></li>
<li><p><span class="math inline">\(\widehat r_k\)</span> in scaled mode.</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="validation-experiment" class="level4">
<h4 class="anchored" data-anchor-id="validation-experiment">Validation experiment</h4>
<section id="experimental-design" class="level5">
<h5 class="anchored" data-anchor-id="experimental-design">Experimental design</h5>
<p>We generated the problem once and ran:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>run<span class="op">(</span><span class="st">"unscaled"</span><span class="op">,</span> <span class="kw">false</span><span class="op">);</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>run<span class="op">(</span><span class="st">"scaled"</span><span class="op">,</span> <span class="kw">true</span><span class="op">);</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Both runs used exactly the same:</p>
<ul>
<li><p>matrix;</p></li>
<li><p>right-hand side;</p></li>
<li><p>random seed;</p></li>
<li><p>dimension <span class="math inline">\(n=100\)</span>;</p></li>
<li><p>condition number <span class="math inline">\(\kappa(A)=10\)</span>;</p></li>
<li><p>precision triple FP16–FP64–FP128;</p></li>
<li><p>stopping criterion and iteration limit.</p></li>
</ul>
<p>The identical initial residual,</p>
<p><span class="math display">\[
\lVert r_0\rVert_\infty
=
1.34744462924774981\times10^{-2},
\]</span></p>
<p>confirmed that scaling did not alter the matrix factorization or initial solution.</p>
<p>The unscaled results also reproduced the previous baseline. Therefore, adding the optional scaling path did not change the original behavior when scaling was disabled.</p>
</section>
<section id="unscaled-result" class="level5">
<h5 class="anchored" data-anchor-id="unscaled-result">Unscaled result</h5>
<p>The unscaled method:</p>
<ul>
<li><p>first lost components at iteration 2;</p></li>
<li><p>lost between 9 and 20 components per later iteration;</p></li>
<li><p>stagnated near <span class="math inline">\(4.17\times10^{-7}\)</span>;</p></li>
<li><p>failed to converge after 20 updates;</p></li>
<li><p>ended with</p></li>
</ul>
<p><span class="math display">\[
\text{final relative correction}
=
1.1685\times10^{-7}.
\]</span></p>
</section>
<section id="scaled-result" class="level5">
<h5 class="anchored" data-anchor-id="scaled-result">Scaled result</h5>
<p>The scaled run produced:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Iteration</th>
<th style="text-align: right;"><span class="math inline">\(\lVert r_k\rVert_\infty\)</span></th>
<th style="text-align: right;">Zeroed by conversion</th>
<th style="text-align: right;">Reduction factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(1.3474\times10^{-2}\)</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">–</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;"><span class="math inline">\(5.3874\times10^{-5}\)</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(250.1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;"><span class="math inline">\(2.8349\times10^{-7}\)</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(190.0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;"><span class="math inline">\(2.1471\times10^{-9}\)</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(132.0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;"><span class="math inline">\(1.1636\times10^{-11}\)</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(184.5\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;"><span class="math inline">\(7.5515\times10^{-14}\)</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(154.1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;"><span class="math inline">\(4.3479\times10^{-16}\)</span></td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(173.7\)</span></td>
</tr>
</tbody>
</table>
<p>No normalized residual component became zero during FP16 conversion.</p>
<p>The residual decreased by</p>
<p><span class="math display">\[
\frac{\lVert r_0\rVert_\infty}
     {\lVert r_6\rVert_\infty}
\approx3.10\times10^{13},
\]</span></p>
<p>or approximately 13.5 decimal orders.</p>
<p>The method converged after seven updates with</p>
<p><span class="math display">\[
\text{final relative correction}
=
9.7687\times10^{-17}.
\]</span></p>
<p>This was below FP64 unit roundoff:</p>
<p><span class="math display">\[
u_{\mathrm{FP64}}
=
2^{-53}
\approx1.1102\times10^{-16}.
\]</span></p>
</section>
<section id="interpretation" class="level5">
<h5 class="anchored" data-anchor-id="interpretation">Interpretation</h5>
<p>The observed reduction factors, between approximately 132 and 250, correspond to contraction factors between roughly</p>
<p><span class="math display">\[
4.0\times10^{-3}
\quad\text{and}\quad
7.6\times10^{-3}.
\]</span></p>
<p>This agrees well with the theoretical scale</p>
<p><span class="math display">\[
\kappa(A)u_{\mathrm{FP16}}
\approx4.88\times10^{-3}.
\]</span></p>
<p>Once the residual-range problem was removed, the algorithm behaved as expected from mixed-precision iterative-refinement theory.</p>
</section>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>The investigation established the following sequence:</p>
<ol type="1">
<li><p>FP16 refinement failed unexpectedly for a well-conditioned problem.</p></li>
<li><p>Bfloat16 succeeded despite having lower significand precision, pointing to an exponent-range problem.</p></li>
<li><p>Direct diagnostics showed that nonzero FP128 residual components were zeroed or severely quantized during FP16 conversion.</p></li>
<li><p>Conversion loss began at the same point as residual stagnation.</p></li>
<li><p>Infinity-norm scaling removed the irrelevant absolute residual magnitude before conversion.</p></li>
<li><p>A controlled scaled-versus-unscaled experiment eliminated all observed conversion-to-zero events.</p></li>
<li><p>The scaled method restored regular convergence and reached FP64 accuracy in seven iterations.</p></li>
</ol>
<p>This is strong validation for the tested system. Broader validation should repeat the comparison over multiple dimensions, condition numbers, and random seeds. Residual scaling addresses residual underflow only; it does not address separate FP16 overflow caused by matrix entries exceeding the FP16 range.</p>
</section>
</section>
</section>
<section id="plotting-convergence-experiments" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="plotting-convergence-experiments"><span class="header-section-number">5.7</span> Plotting Convergence Experiments</h2>
<p>The script</p>
<pre class="text"><code>code/scripts/plot_convergence.py</code></pre>
<p>generates convergence-history and summary plots from one mixed-precision iterative-refinement CSV file.</p>
<p>It is designed to be reusable for different:</p>
<ul>
<li>matrix generators;</li>
<li>right-hand-side or solution-generation modes;</li>
<li>precision combinations.</li>
</ul>
<p>The input CSV is selected using a command-line argument, so a separate plotting script is not needed for each experiment.</p>
<section id="expected-csv-format" class="level3">
<h3 class="anchored" data-anchor-id="expected-csv-format">Expected CSV format</h3>
<p>The CSV file must contain the columns:</p>
<pre class="text"><code>kappa
iteration
forward_error_inf
backward_error_inf
rel_correction
converged
total_iterations
final_rel_correction</code></pre>
<p>Each row describes one iterate for one condition number.</p>
<p>The usual relationship is:</p>
<pre class="text"><code>iteration 0  → initial solution x0
iteration 1  → solution x1 after the first correction
iteration 2  → solution x2 after the second correction
...</code></pre>
</section>
<section id="generated-plots" class="level3">
<h3 class="anchored" data-anchor-id="generated-plots">Generated plots</h3>
<p>For every input CSV, the script generates six plots.</p>
<section id="convergence-histories" class="level4">
<h4 class="anchored" data-anchor-id="convergence-histories">Convergence histories</h4>
<ol type="1">
<li>Relative forward error against refinement iteration.</li>
<li>Normwise backward error against refinement iteration.</li>
<li>Relative correction norm against refinement iteration.</li>
</ol>
<p>Each condition number is displayed as a separate curve.</p>
</section>
<section id="summary-plots" class="level4">
<h4 class="anchored" data-anchor-id="summary-plots">Summary plots</h4>
<ol start="4" type="1">
<li>Final forward and backward errors against condition number.</li>
<li>Best forward and backward errors attained at any iteration.</li>
<li>Total refinement iterations against condition number.</li>
</ol>
<p>The best-attained-error plot is useful when an iteration initially improves and later deteriorates. For example, a difficult () problem may attain its best forward error around iteration 7 but have a worse result at iteration 20.</p>
<p>The script also prints a numerical summary containing:</p>
<ul>
<li>condition number;</li>
<li>convergence flag;</li>
<li>total iterations;</li>
<li>final forward error;</li>
<li>final backward error;</li>
<li>final relative correction;</li>
<li>best forward and backward errors;</li>
<li>iterations at which the best errors occurred.</li>
</ul>
</section>
</section>
<section id="logarithmic-plots-and-zero-values" class="level3">
<h3 class="anchored" data-anchor-id="logarithmic-plots-and-zero-values">Logarithmic plots and zero values</h3>
<p>The error histories use logarithmic vertical axes. Since zero cannot be displayed on a logarithmic scale, the script replaces nonpositive plotting values with <code>NaN</code>.</p>
<p>This affects only plotting. The original CSV data is not modified.</p>
<p>Consequently, a curve or point with an exactly zero error may disappear from a logarithmic plot.</p>
</section>
<section id="command-line-interface" class="level3">
<h3 class="anchored" data-anchor-id="command-line-interface">Command-line interface</h3>
<p>The general invocation is:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py CSV_FILE <span class="dt">\</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Description of experiment"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If the terminal is already inside <code>code/</code>, use:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/plot_convergence.py CSV_FILE <span class="dt">\</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Description of experiment"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The script first checks whether <code>CSV_FILE</code> is a direct path. If it is not found there, it looks under:</p>
<pre class="text"><code>code/results/raw/</code></pre>
<p>The plots are written to:</p>
<pre class="text"><code>code/results/plots/</code></pre>
</section>
<section id="default-behavior" class="level3">
<h3 class="anchored" data-anchor-id="default-behavior">Default behavior</h3>
<p>The CSV argument is optional. If no filename is provided, the script uses:</p>
<pre class="text"><code>convergence_fp16_fp64_fp128.csv</code></pre>
<p>Therefore:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>is equivalent to:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    convergence_fp16_fp64_fp128.csv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="output-tags" class="level3">
<h3 class="anchored" data-anchor-id="output-tags">Output tags</h3>
<p>The output tag is normally derived automatically from the CSV filename.</p>
<p>For example, from:</p>
<pre class="text"><code>convergence_random_spd_fp16_fp64_fp128.csv</code></pre>
<p>the script removes the initial <code>convergence_</code> and obtains:</p>
<pre class="text"><code>random_spd_fp16_fp64_fp128</code></pre>
<p>It then generates filenames such as:</p>
<pre class="text"><code>convergence_forward_error_random_spd_fp16_fp64_fp128.png
convergence_backward_error_random_spd_fp16_fp64_fp128.png
convergence_rel_correction_random_spd_fp16_fp64_fp128.png
summary_final_errors_random_spd_fp16_fp64_fp128.png
summary_best_errors_random_spd_fp16_fp64_fp128.png
summary_iterations_random_spd_fp16_fp64_fp128.png</code></pre>
<p>A custom output tag can be supplied with:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="ex">--tag</span> custom_name</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>For example:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    convergence_random_spd_fp16_fp64_fp128.csv <span class="dt">\</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--tag</span> random_spd_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="descriptive-plot-labels" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-plot-labels">Descriptive plot labels</h3>
<p>The optional <code>--label</code> argument is added to plot titles:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="ex">--label</span> <span class="st">"Random dense SPD"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This produces titles such as:</p>
<pre class="text"><code>Random dense SPD: relative forward error, infinity norm vs. refinement iteration</code></pre>
<p>The label does not affect the output filenames.</p>
</section>
<section id="matrix-family-examples" class="level3">
<h3 class="anchored" data-anchor-id="matrix-family-examples">Matrix-family examples</h3>
<section id="block-rotated-spd" class="level4">
<h4 class="anchored" data-anchor-id="block-rotated-spd">Block-rotated SPD</h4>
<div class="sourceCode" id="cb57"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>    convergence_fp16_fp64_fp128.csv <span class="dt">\</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Block-rotated SPD"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="random-dense-spd" class="level4">
<h4 class="anchored" data-anchor-id="random-dense-spd">Random dense SPD</h4>
<div class="sourceCode" id="cb58"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>    convergence_random_spd_fp16_fp64_fp128.csv <span class="dt">\</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Random dense SPD"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="random-svd" class="level4">
<h4 class="anchored" data-anchor-id="random-svd">Random SVD</h4>
<div class="sourceCode" id="cb59"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>    convergence_random_svd_fp16_fp64_fp128.csv <span class="dt">\</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Random SVD"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="encoding-the-solution-or-rhs-mode" class="level3">
<h3 class="anchored" data-anchor-id="encoding-the-solution-or-rhs-mode">Encoding the solution or RHS mode</h3>
<p>The test-problem infrastructure supports three modes:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode cpp code-with-copy"><code class="sourceCode cpp"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>RightHandSideMode<span class="op">::</span>ones_solution</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>RightHandSideMode<span class="op">::</span>random_sign_solution</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>RightHandSideMode<span class="op">::</span>random_normal_rhs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>These correspond to:</p>
<ul>
<li>construct (x=(1,,1)^T) and form (b=Ax);</li>
<li>construct random (x_i) and form (b=Ax);</li>
<li>generate (b_iN(0,1)) and compute a high-precision reference solution.</li>
</ul>
<p>The third mode uses a normal distribution, not a uniform distribution.</p>
<p>It is sensible to encode this choice in the CSV filename. A consistent naming scheme is:</p>
<pre class="text"><code>convergence_&lt;matrix-family&gt;_&lt;rhs-mode&gt;_&lt;factor&gt;_&lt;work&gt;_&lt;residual&gt;.csv</code></pre>
<p>For example:</p>
<pre class="text"><code>convergence_random_spd_x_ones_fp16_fp64_fp128.csv
convergence_random_spd_x_random_signs_fp16_fp64_fp128.csv
convergence_random_spd_b_random_normal_fp16_fp64_fp128.csv</code></pre>
<p>The plotting script automatically retains the RHS mode as part of the output tag. No code change is needed.</p>
</section>
<section id="examples-for-the-three-modes" class="level3">
<h3 class="anchored" data-anchor-id="examples-for-the-three-modes">Examples for the three modes</h3>
<section id="all-ones-solution" class="level4">
<h4 class="anchored" data-anchor-id="all-ones-solution">All-ones solution</h4>
<div class="sourceCode" id="cb63"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>    convergence_random_spd_x_ones_fp16_fp64_fp128.csv <span class="dt">\</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Random SPD, ones solution"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This produces files such as:</p>
<pre class="text"><code>convergence_forward_error_random_spd_x_ones_fp16_fp64_fp128.png</code></pre>
</section>
<section id="random-sign-solution" class="level4">
<h4 class="anchored" data-anchor-id="random-sign-solution">Random-sign solution</h4>
<div class="sourceCode" id="cb65"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>    convergence_random_spd_x_random_signs_fp16_fp64_fp128.csv <span class="dt">\</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Random SPD, random-sign solution"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This produces files such as:</p>
<pre class="text"><code>convergence_forward_error_random_spd_x_random_signs_fp16_fp64_fp128.png</code></pre>
</section>
<section id="random-normal-right-hand-side" class="level4">
<h4 class="anchored" data-anchor-id="random-normal-right-hand-side">Random-normal right-hand side</h4>
<div class="sourceCode" id="cb67"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> code/scripts/plot_convergence.py <span class="dt">\</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>    convergence_random_spd_b_random_normal_fp16_fp64_fp128.csv <span class="dt">\</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--label</span> <span class="st">"Random SPD, normally distributed right-hand side"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This produces files such as:</p>
<pre class="text"><code>convergence_forward_error_random_spd_b_random_normal_fp16_fp64_fp128.png</code></pre>
</section>
</section>
<section id="what-the-script-detects-automatically" class="level3">
<h3 class="anchored" data-anchor-id="what-the-script-detects-automatically">What the script detects automatically</h3>
<p>The script automatically derives an output tag from the filename. It does not semantically interpret components such as:</p>
<pre class="text"><code>random_spd
x_ones
x_random_signs
b_random_normal
fp16_fp64_fp128</code></pre>
<p>Therefore:</p>
<ul>
<li>output filenames are generated correctly automatically;</li>
<li>the same plots are generated for every mode;</li>
<li>a human-readable title should currently be supplied through <code>--label</code>.</li>
</ul>
<p>Automatic semantic interpretation could be added later, but it is not necessary for the current workflow.</p>
</section>
<section id="recording-metadata-inside-the-csv" class="level3">
<h3 class="anchored" data-anchor-id="recording-metadata-inside-the-csv">Recording metadata inside the CSV</h3>
<p>Encoding the experiment configuration in the filename is useful, but the CSV should eventually also record metadata such as:</p>
<pre class="text"><code>matrix_family
rhs_mode
matrix_seed_u
matrix_seed_v
vector_seed</code></pre>
<p>For example:</p>
<pre class="text"><code>matrix_family,rhs_mode,matrix_seed_u,matrix_seed_v,vector_seed,kappa,...
random_spd,x_random_signs,42,137,2718,10,...</code></pre>
<p>This makes the experiment self-describing even if the file is renamed.</p>
</section>
<section id="later-comparison-plots" class="level3">
<h3 class="anchored" data-anchor-id="later-comparison-plots">Later comparison plots</h3>
<p><code>plot_convergence.py</code> plots one CSV dataset at a time. It should remain focused on that task.</p>
<p>A later script, for example</p>
<pre class="text"><code>code/scripts/plot_compare_generators.py</code></pre>
<p>or</p>
<pre class="text"><code>code/scripts/plot_compare_rhs_modes.py</code></pre>
<p>can place multiple experiments on the same figures.</p>
<p>Possible comparisons include:</p>
<ul>
<li>block-rotated SPD versus random SPD versus random SVD;</li>
<li>all-ones versus random-sign solutions;</li>
<li>prescribed (x) versus random-normal (b);</li>
<li>different precision triples;</li>
<li>different random seeds.</li>
</ul>
<p>Thus, the intended organization is:</p>
<pre class="text"><code>plot_convergence.py
    → detailed plots for one experiment

plot_compare_generators.py
    → compare matrix families

plot_compare_rhs_modes.py
    → compare solution/RHS-generation strategies</code></pre>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notes/mixed_ir.html" class="pagination-link" aria-label="Implementation of the Mixed IR Algorithm">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Implementation of the Mixed IR Algorithm</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/experiment_plan.html" class="pagination-link" aria-label="Mixed-Precision Iterative Refinement: Experiment Plan">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mixed-Precision Iterative Refinement: Experiment Plan</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>